const data = [
  {
    id: 1,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 2,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 3,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 4,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 5,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 6,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 7,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 8,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 9,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 10,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 11,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
  {
    id: 12,
    title: "Biker Jacket",
    description: "Bikers Jacket made from a high quality genuin leather etc.",
    img: "./Images/clothing.webp",
    categories: ["new", "sale", "man"],
    size: ["xs", "s", "m", "l", "xl"],
    color: ["black", "gray", "tan"],
    price: 5000,
    onStock: true,
  },
];

export default data